### ISSUE TITLE
Error Downloading "TUDM - The Ultimate Dodge Mod v4 x64.rar" when installing modlist

### ISSUE THREAD

**Issue by gx86** [SovnSkyrim/QWEST#20]
Hello,

There appears to have been a change with the availability of "TUDM - The Ultimate Dodge Mod v4 x64.rar" at least as of today.  When trying to find solutions to the error from the log snippit below I found other ModLists that are having issues with the same resource as of today.

Thank you.

> 40.53 - Loaded permissions for 532 servers and 253 Google Drive files
40.54 - File hash check (-42) 37981c9dfc65fda817cec6445b33f008a7dfd5a2584f793040ec150a6bcce914
40.6 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
41.74 - Hashed download is incorrect
41.74 - Loading for alternative to U659DN1scQM=
41.92 - No alternative for U659DN1scQM= could be found
42 - Hashing Remaining Archives
42 - Looking for files to hash
42.2 - Found 1006 total files, 981 matching filesize
42.74 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
42.74 - Cannot continue, was unable to download one or more archives
42.74 - File hash check (-42) 37981c9dfc65fda817cec6445b33f008a7dfd5a2584f793040ec150a6bcce914
42.83 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
42.95 - File hash check (-42) 37981c9dfc65fda817cec6445b33f008a7dfd5a2584f793040ec150a6bcce914

**Comment by Raneck** [comment]
Hello, 

Same here. After several hours of manual download. Did you have a solution ? 

Thanks for the good work on your list by the way.

**Comment by rene0121** [comment]
ran into this same problem with other mod lists, need to download the mod manually.I ripped this link from the issues report from Elysium, https://drive.google.com/file/d/0B2VgBVA9jE6RTjJiYnRTTE9qRUE/view?resourcekey=0-atMbrLF_HPd3ogbiZaBiXw download and place manually into QWEST/downloads folder then start installation again and it should work fine.

**Comment by gx86** [comment]
> ran into this same problem with other mod lists, need to download the mod manually.I ripped this link from the issues report from Elysium, https://drive.google.com/file/d/0B2VgBVA9jE6RTjJiYnRTTE9qRUE/view?resourcekey=0-atMbrLF_HPd3ogbiZaBiXw download and place manually into QWEST/downloads folder then start installation again and it should work fine.

Thank you @rene0121 for sharing that !

**Comment by gx86** [comment]
> Hello,
> 
> Same here. After several hours of manual download. Did you have a solution ?
> 
> Thanks for the good work on your list by the way.

@Raneck the fix from @rene0121 worked for me.
